=== DaniellaGeorgieva/VeDaTravel/validation.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xlink="http://www.w3.org/1999/xlink"
           xmlns="http://www.w3schools.com"
           targetNamespace="http://www.w3schools.com"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
			
			<!-- <xs:keyref name="tripRef" refer="keyTrip">
				<xs:selector xpath="trips_catalog/trips/trip"/>
				<xs:field xpath="region"/>
			</xs:keyref> -->
			
			<!-- Attributes of trip - region -->
			<xs:simpleType name="region">
				<xs:restriction base="xs:string">
					<xs:enumeration value="Европа" />
					<xs:enumeration value="Азия" />
					<xs:enumeration value="Северна Америка" />
					<xs:enumeration value="Африка" />
				</xs:restriction>
			</xs:simpleType>
			
			<!-- Attributes of trip - destination -->
			<xs:simpleType name="destination_trip">
				<xs:restriction base="xs:string">
					<xs:pattern value="[А-Я][а-я]+(\s)?([А-Я][а-я]+)?"/>
				</xs:restriction>
			</xs:simpleType>
			
			<!-- Attributes of trip - id -->
			<xs:simpleType name="id_trip">
				<xs:restriction base="xs:ID">
					<xs:pattern value="t[0-9]+" />
				</xs:restriction>
			</xs:simpleType>
			
			<!-- Attributes of image - id -->
			<xs:simpleType name="id_image">
				<xs:restriction base="xs:string">
					<xs:pattern value="([A-Z][a-z]+)+"/>
				</xs:restriction>
			</xs:simpleType>

			<!-- Attributes of map -->
			<xs:simpleType name="hrefType">
				<xs:restriction base="xs:anyURI"/>
			</xs:simpleType>

			<xs:simpleType name="mapType">
				<xs:restriction base="xs:string"/>
			</xs:simpleType>

			<xs:simpleType name="showType">
				<xs:restriction base="xs:string">
					<xs:enumeration value="embed"/>
					<xs:enumeration value="simple"/>
				</xs:restriction>
			</xs:simpleType>
			
			<!-- Simple Elements -->
			<xs:element name="title" type="xs:string"/>
			<xs:element name="startDate" type="xs:date"/>
			<xs:element name="endDate" type="xs:date"/>
			<xs:element name="price" type="xs:positiveInteger"/>
			<xs:element name="description">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:whiteSpace value="collapse"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!-- <xs:element name="map" type="xs:string"/> -->
			<xs:element name="stop" type="xs:string"/>
			<xs:element name="touristName">
				<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:whiteSpace value="collapse"/>
						</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!-- <xs:element name="tourist"/> -->
			<!-- Complex elements -->
			
			<xs:element name="trips_catalog">
				<!-- <xs:complexType>
					<xs:sequence>
						<xs:element ref="trips"/>
						<xs:element name="listOfTourists">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="tourist" maxOccurs="unbounded">
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:string">
												<xs:attribute name="t_id" type="xs:IDREF" use="required"/>
												<xs:attribute name="sd_id" type="xs:IDREF" use="required"/>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					</xs:sequence>
				</xs:complexType> -->
				<xs:key name="keyTrips">
					<xs:selector xpath="trips_catalog"/>
					<xs:field xpath="trips/trip"/>
				</xs:key> 	
			</xs:element>
			
			<xs:element name="trips">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="trip" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>


			<xs:element name="photo">
				<xs:complexType>
					<xs:sequence>
                		<xs:element name="src">
							<xs:complexType>
								<xs:attribute name="url" type="xs:string"/>
							</xs:complexType>
						</xs:element>
            		</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="trip">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="title"/>
						<xs:element ref="startDate"/>
						<xs:element ref="endDate"/>
						<xs:element ref="price"/>
						<xs:element ref="description"/>
						<xs:element ref="photo"/>
						<!-- <xs:element name="map">
							<xs:complexType>
									<xs:attribute name="type" type="mapType" use="required"/>
									<xs:attribute name="href" type="hrefType" use="required"/>
									<xs:attribute name="show" type="showType" use="required"/>
							</xs:complexType>
						</xs:element> -->
						<xs:element name="route">
							<xs:complexType>
								<xs:sequence> 
								    <xs:element ref="stop" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						
						<!-- <xs:element name="photo">
							<xs:complexType>
								<xs:attribute name="id" type="xs:ID" use="required"/>
							</xs:complexType>
						</xs:element> -->
						<xs:element name="listTourists">
							<xs:complexType>
								<xs:sequence>
								    <xs:element ref="touristName" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="id_trip" use="required"/>
					<xs:attribute name="region" type="region" use="required"/>
					<xs:attribute name="destination" type="destination_trip" use="required"/>
				</xs:complexType>
				<xs:key name="keyTrip">
				        <xs:selector xpath="trip"/>
				        <xs:field xpath="@id"/>
				        <xs:field xpath="@region"/>
				        <xs:field xpath="@destination"/>
			    </xs:key>
				<xs:unique name="tripUnique">
						<xs:selector xpath="trip"/>
						<xs:field xpath="@id"/>
						<xs:field xpath="@destination"/>
					</xs:unique>
			</xs:element>
			
</xs:schema>

=== DaniellaGeorgieva/VeDaTravel/description.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE trips_catalog [
  <!ENTITY imgSpain SYSTEM "https://www.state.gov/wp-content/uploads/2023/07/shutterstock_1656628171v2-2107x1406.jpg" NDATA jpg>
  <!ENTITY imgNorway SYSTEM "https://hips.hearstapps.com/hmg-prod/images/city-of-alesund-norway-royalty-free-image-1620376302.?crop=0.670xw:1.00xh;0.298xw,0&resize=640:*" NDATA jpg>
  <!ENTITY imgNY SYSTEM "https://res.klook.com/image/upload/Mobile/City/szhx3ytpgfnhpbmsngk0.jpg" NDATA jpg>
  <!ENTITY imgLA SYSTEM "https://www.visittheusa.com/sites/default/files/styles/hero_l/public/images/hero_media_image/2017-01/Getty_515070156_EDITORIALONLY_LosAngeles_HollywoodBlvd_Web72DPI_0.jpg?h=0a8b6f8b&itok=lst_2_5d" NDATA jpg>
  <!ENTITY imgEgypt SYSTEM "https://media.istockphoto.com/id/1397759783/photo/pyramid-complex-in-aswan-city-by-the-nile-aerial-view-egypt.webp?b=1&s=170667a&w=0&k=20&c=JI4VGOwiIZDm23QL10akKGLTmjdgyI3t-E3Mf5N4LBA=" NDATA jpg>
  <!ENTITY imgJapan SYSTEM "https://www.state.gov/wp-content/uploads/2019/04/Japan-2107x1406.jpg" NDATA jpg>
  <!ENTITY imgIndia SYSTEM "https://media.istockphoto.com/id/1146517111/photo/taj-mahal-mausoleum-in-agra.jpg?s=612x612&w=0&k=20&c=vcIjhwUrNyjoKbGbAQ5sOcEzDUgOfCsm9ySmJ8gNeRk=" NDATA jpg>
  <!NOTATION jpg PUBLIC "jpg">
]>
<?xml-stylesheet type="text/xsl" href="project.xsl"?>

<trips_catalog
		xmlns="http://www.w3schools.com"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com validation.xsd">
		<trips>
			<trip xmlns:xlink="http://www.w3.org/1999/xlink" id="t1" region="Европа" destination="Испания">
				<title>Испания - страстна и разнообразна</title>
				<startDate>2024-02-26</startDate>
				<endDate>2024-02-29</endDate>
				<price>1890</price>
				<description>
				Можете ли да си представите, че сте заобиколени от прекрасно синьо море,
				изобилие от палми и великолепни  плажове с бял пясък? Да, това е Испания!
				Палещо слънце, горещи ритми, средиземноморска кухня и луксозни хотели – всичко това ви очаква тук.
				</description>
				<map type="simple" 
				     href="https://maps.app.goo.gl/ohpDJ9tV6ggsAp2M6"
				     show="embed"/>
				<route>
					<stop>Мадрид</stop>
					<stop>Барселона</stop>
				</route>
				<listTourists>
					<touristName> Ванеса Григорова </touristName>
					<touristName> Милен Григоров </touristName>
				</listTourists>
			</trip>
			<trip id="t2" region="Европа" destination="Норвегия">
				<title>Норвегия - впечатляващи фиордове, вековни планини и северно сияние</title>
				<startDate>2024-07-04</startDate>
				<endDate>2024-07-10</endDate>
				<price>3990</price>
				<description>
				Впуснете се в едно изключително и незабравимо преживяване, посещавайки най-красивите заливи на света - фиордите в Норвегия.
				</description>
				<map type="simple" 
				     href="https://maps.app.goo.gl/jHPD5m8MmYFsEUme9"
				     show="embed"/>
				<route>
					<stop>Осло</stop>
					<stop>Берген</stop>
					<stop>Тромсьо</stop>
				</route>
				<listTourists>
					<touristName> Пламен Найденов </touristName>
					<touristName> Велислава Крумова </touristName>
					<touristName> Преслава Андонова </touristName>
					<touristName> Илия Стоев </touristName>
				</listTourists>
			</trip>
			<trip id="t3" region="Северна Америка" destination="Ню Йорк">
				<title>Забавления в Голямата ябълка - Ню Йорк, САЩ</title>
				<startDate>2024-08-05</startDate>
				<endDate>2024-08-25</endDate>
				<price>5890</price>
				<description>
				Изживейте американската мечта и усетете нюйоркския дух, като посетите Статуята на Свободата и Таймс Скуеър. Ню Йорк ви предлага уникален културен и градски опит.
				</description>
				<map type="simple" 
				     href="https://maps.app.goo.gl/hNs1rCPN7Rc81BYx7"
				     show="embed"/>
				<route>
					<stop>Манхатън</stop>
					<stop>Статуята на свободата</stop>
					<stop>Емпайър Стейт Билдинг</stop>
					<stop>Таймс Скуеър</stop>
					<stop>Сентръл Парк</stop>
				</route>
				<listTourists>
					<touristName> Даниела Георгиева </touristName>
					<touristName> Божидар Абаджиев </touristName>
					<touristName> Стилиян Стоянов </touristName>
					<touristName> Гергана Куртева </touristName>
				</listTourists>
			</trip>
			<trip id="t4" region="Северна Америка" destination="Лос Анджелис">
				<title>Лос Анджелис - градът на мечтите и звездите</title>
				<startDate>2024-08-02</startDate>
				<endDate>2024-08-20</endDate>
				<price>5990</price>
				<description>
				Потопете се в най-откровените си желания в града на ангелите, където слънцето, знаменитостите и културата се сливат.
				Разгледайте Холивидския булевард, посетете Грифит парк и обиколете световноизвестния Музей на изкуствата(LACMA).
				</description>
				<map type="simple" 
				     href="https://maps.app.goo.gl/32aNLnuKhwnJjjd1A"
				     show="embed"/>
				<route>
					<stop>Холивуд</stop>
					<stop>Бевърли Хилс</stop>
					<stop>Санта Моника</stop>
					<stop>Обсерватория Грифит</stop>
					<stop>Сънсет Стрип Авеню</stop>
				</route>
				<listTourists>
					<touristName> Никола Георгиев </touristName>
					<touristName> Дарина Стоянова </touristName>
				</listTourists>
			</trip>
			<trip id="t5" region="Африка" destination="Египет">
				<title>На сафари в Египет</title>
				<startDate>2024-05-03</startDate>
				<endDate>2024-05-13</endDate>
				<price>2490</price>
				<description>
				Египет е страна с богата история и култура, обгърната от мистика и величие. Посетете пирамидите в Гиза, откриййте древните храмове в Луксор и Карнак и се потопете
				в богатото религиозно и историческо наследство.
				</description>
				<map type="simple" 
				     href="https://www.google.com/maps/place/%D0%95%D0%B3%D0%B8%D0%BF%D0%B5%D1%82/@26.9060999,30.8768375,6z/data=!4m6!3m5!1s0x14368976c35c36e9:0x2c45a00925c4c444!8m2!3d26.820553!4d30.802498!16zL20vMDJrNTQ?entry=ttu"
				     show="embed"/>
				<route>
					<stop>Кайро</stop>
					<stop>Луксор</stop>
					<stop>Пирамидите в Гиза и Сфинкса</stop>
					<stop>Абу Симбел</stop>
				</route>
				<listTourists>
					<touristName> Ричард Илиев </touristName>
					<touristName> Леонардо Петров </touristName>
					<touristName> Мерилин Иванова </touristName>
				</listTourists>
			</trip>
			<trip id="t6" region="Азия" destination="Япония">
				<title>Япония - страната на изгряващото слънце</title>
				<startDate>2024-04-12</startDate>
				<endDate>2024-04-22</endDate>
				<price>5990</price>
				<description>
				Екскурзията в Япония ще ви отведе в страна, където традицията среща съвременноста. Посетете столицата Токио с нейните светещи реклами
				и традиционни храмове като Сензо-джи. Япония предлага уникално разнообразие от култура, гастрономия и природа.
				</description>
				<map type="simple" 
				     href="https://maps.app.goo.gl/EngSjKqs6ZhxHKQF6"
				     show="embed"/>
				<route>
					<stop>Токио</stop>
					<stop>Киото</stop>
					<stop>Остров Мияджима</stop>
				</route>
				<listTourists>
					<touristName> Адриана Атанасова </touristName>
					<touristName> Константин Тодоров </touristName>
					<touristName> Радина Косева</touristName>
				</listTourists>
			</trip>
			<trip id="t7" region="Азия" destination="Индия">
				<title>Магията на Индия</title>
				<startDate>2024-09-12</startDate>
				<endDate>2024-09-22</endDate>
				<price>5890</price>
				<description>
				Пригответе се за експлозия на сетивата в Индия. Посетете Тадж Махал, опитайте дивите аромати и вкусове на индийската кухня и изживейте
				цветната култура на Варанаси край светите води на Ганга.
				</description>
				<map type="simple" 
				     href="https://maps.app.goo.gl/pHEqAYA1jUQus33a6"
				     show="embed"/>
				<route>
					<stop>Делхи</stop>
					<stop>Тадж Махал</stop>
					<stop>Мумбай</stop>
				</route>
				<listTourists>
					<touristName> Петя Костадинова </touristName>
					<touristName> Рикардо Тодоров </touristName>
					<touristName> Николина Димитрова </touristName>
				</listTourists>
			</trip>
		</trips>
</trips_catalog>
